// app/cover-image.tsx
import ContentfulImage from "../lib/contentful-image";
import Link from "next/link";

function cn(...classes: any[]) {
  return classes.filter(Boolean).join(" ");
}

export default function CoverImage({
  title,
  url,
  slug,
}: {
  title: string;
  url: string;
  slug?: string;
}) {
  const image = (
    <ContentfulImage
      alt={`Cover Image for ${title}`}
      priority
      width={2000}
      height={1000}
      className={cn("shadow-small", {
        "hover:shadow-medium transition-shadow duration-200": slug,
      })}
      src={url}
    />
  );

  return (
    <div className="sm:mx-0">
      {slug ? (
        <Link href={`/p/${slug}`} aria-label={title}>
          {image}
        </Link>
      ) : (
        image
      )}
    </div>
  );
}

// app/components/CoverImage.vue
<script setup lang="ts">
interface Props {
  title: string
  url: string
  slug?: string
}

const props = defineProps<Props>()
</script>

<template>
  <div class="cover-image-wrapper">
    <NuxtLink v-if="slug" :to="`/p/${slug}`" :aria-label="title">
      <ContentfulImage
        :alt="`Cover Image for ${title}`"
        :width="1200"
        :height="800"
        class="cover-image clickable"
        :src="url"
      />
    </NuxtLink>
    <ContentfulImage
      v-else
      :alt="`Cover Image for ${title}`"
      :width="1200"
      :height="800"
      class="cover-image"
      :src="url"
    />
  </div>
</template>
