// app/p/[slug]/page.tsx
import Link from "next/link";
import { draftMode } from "next/headers";

import CoverImage from "../../cover-image";

import { Markdown } from "@/lib/markdown";
import { getAllProjects, getSingleProject } from "@/lib/api";

export async function generateStaticParams() {
  const projects = await getAllProjects(true);

  return projects.map((item) => ({
    slug: item.slug,
  }));
}

function Video({url, title} : {url: string, title: string}) {
  return (
    <div className="border border-2 border-slate-700">
      {/* <h4>{title}</h4> */}
      <video autoPlay loop muted width="100%" height="auto" controls >
        <source src={url} type="video/mp4" />
        <track
          src={url}
          kind="subtitles"
          label="English"
        />
        Your browser does not support the video tag.
      </video>
    </div>
    
  )
}

export default async function ProjectPage({
  params,
}: {
  params: { slug: string };
}) {
  const { isEnabled } = draftMode();
  const project = await getSingleProject(params.slug, isEnabled);
  
  return (
    <div className="container mx-auto px-5">
      <h2 className="text-xl md:text-xl font-bold tracking-tight md:tracking-tight leading-tight mt-8 mb-8">
        <Link href="/" className="cursor-pointer bg-slate-100 p-2 underline font-bold tracking-tight">
          Home
        </Link>
      </h2>
      <article>
        <h1 className="text-xl md:text-3xl lg:text-4xl font-bold tracking-tight leading-tight md:leading-none mb-4 md:mb-8 md:text-left">
          {project.title}
        </h1>
        
        {/* Technology stack badges */}
        <div className="mb-4 md:mb-8 sm:mx-0">
          {project.techTags.map((tag: string, key: number) => (
            <span 
              key={key}
              className="text-center justify-center text-xs font-medium px-4 py-2 py-0.5 rounded-full mr-2
              text-yellow-800 ring-1 ring-inset ring-yellow-600/20 bg-yellow-50"
            >
            { tag }
          </span>
          ))}
        </div>
          
        {/* Project Description */}
        <div className="mx-auto mb-2 md:mb-4">
          <div className="prose tracking-tight text-sm leading-6">
            { project.bodyContent && <Markdown content={project.bodyContent} /> }
          </div>
        </div>
        
        {project.demoVideo && (
          <div className="mb-4 md:mb-8">
            <Video 
              title={project.demoVideo.title} 
              url={project.demoVideo.url} 
            />
          </div>
        )}
        
        {/* External Project Link, if present */}
        {project.externalUrl && ( 
          <Link
            href={project.externalUrl}
            className="items-center rounded-md text-white
            bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800
            font-bold tracking-tighter shadow-black hover:drop-shadow-sm
            transform hover:-translate-y-0.5 
            py-2 px-4 lg:px-3 duration-400 transition ease-out"
          >
            Project Demo
          </Link>
        )}
        
        {/* Hero image */}
        <div className="max-w-2xl mt-8 mb-8 md:mb-16 sm:mx-0">
          <CoverImage title={project.title} url={project.heroImage.url} />
        </div>
       
      </article>
    </div>
  );
}

// app/pages/p/[slug].vue
<script setup lang="ts">
import type { ProjectExtended } from '~/types'

const route = useRoute()
const { isPreview } = useContentfulPreview()

const { data: project } = await useAsyncData<ProjectExtended>(
  `project-${route.params.slug}`,
  () => $fetch(`/api/projects/${route.params.slug}`, {
    query: { preview: isPreview.value }
  })
)

// Set page title
useHead({
  title: project.value?.title ? `${project.value.title} - Mihai Peteu` : 'Project - Mihai Peteu'
})
</script>

<template>
  <div class="container">
    <div class="project-page">
      <NuxtLink to="/" class="back-link">
        Home
      </NuxtLink>

      <article v-if="project">
        <h1 class="project-title">
          {{ project.title }}
        </h1>

        <!-- Technology stack badges -->
        <div v-if="project.tags" class="tech-tags">
          <span
            v-for="(tag, index) in project.tags.split(',').map(t => t.trim())"
            :key="index"
            class="tech-tag"
          >
            {{ tag }}
          </span>
        </div>

        <!-- Project Description / Body Content -->
        <div v-if="project.bodyContent" class="prose">
          <RichTextRenderer :content="project.bodyContent" />
        </div>

        <!-- Demo Video -->
        <Video
          v-if="project.demoVideo"
          :title="project.demoVideo.title"
          :url="project.demoVideo.url"
        />

        <!-- External Project Link -->
        <NuxtLink
          v-if="project.externalUrl"
          :to="project.externalUrl"
          class="external-link"
          target="_blank"
          rel="noopener noreferrer"
        >
          More Info
        </NuxtLink>

        <!-- Hero image -->
        <div class="hero-image-wrapper">
          <CoverImage
            :title="project.title"
            :url="project.heroImage.url"
          />
        </div>


        <!-- Image Gallery -->
        <div v-if="project.imageGalleryCollection?.items?.length" class="image-gallery">
          <div
            v-for="(image, index) in project.imageGalleryCollection.items"
            :key="index"
            class="gallery-item"
          >
            <NuxtImg
              :src="image.url"
              :alt="image.description || image.title"
              loading="lazy"
            />
          </div>
        </div>

      </article>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.project-page {
  padding-top: 2rem;
}

.back-link {
  display: inline-block;
  background-color: #f1f5f9;
  padding: 0.5rem;
  text-decoration: underline;
  font-weight: 700;
  letter-spacing: -0.025em;
  margin-bottom: 2rem;
}

.project-title {
  font-size: 1.25rem;
  font-weight: 700;
  letter-spacing: -0.025em;
  line-height: 1.25;
  margin-bottom: 1rem;

  @media (min-width: 768px) {
    font-size: 1.875rem;
    margin-bottom: 2rem;
  }

  @media (min-width: 1024px) {
    font-size: 2.25rem;
  }
}

.tech-tags {
  margin-bottom: 1rem;

  @media (min-width: 768px) {
    margin-bottom: 2rem;
  }
}

.tech-tag {
  display: inline-block;
  text-align: center;
  font-size: 0.75rem;
  font-weight: 500;
  padding: 0.25rem 1rem;
  margin-right: 0.5rem;
  margin-bottom: 0.5rem;
  color: #854d0e;
  background-color: #fefce8;
  border: 1px solid rgba(202, 138, 4, 0.2);
}

.prose {
  letter-spacing: -0.025em;
  font-size: 0.875rem;
  line-height: 1.75;
  margin-bottom: 1rem;

  @media (min-width: 768px) {
    margin-bottom: 1.5rem;
  }

  :deep(p) {
    margin-bottom: 1rem;
  }

  :deep(img) {
    width: 100%;
    height: auto;
    margin: 1rem 0;
  }

  :deep(a) {
    color: #3b82f6;
    text-decoration: underline;

    &:hover {
      color: #1d4ed8;
      opacity: 1;
    }
  }
}

.external-link {
  display: inline-flex;
  align-items: center;
  padding: 0.5rem 1rem;
  border-radius: 12px;
  color: white;
  background: linear-gradient(to bottom right, #9333ea, #3b82f6);
  font-weight: 700;
  letter-spacing: -0.05em;
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.05);
  transition:
    transform 0.2s ease-out,
    box-shadow 0.2s ease-out;

  &:hover {
    opacity: 1;
    background: linear-gradient(to bottom left, #9333ea, #3b82f6);
    transform: translateY(-2px);
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
  }
}

.hero-image-wrapper {
  max-width: 42rem;
  margin-top: 2rem;
  margin-bottom: 2rem;

  @media (min-width: 768px) {
    margin-bottom: 4rem;
  }
}

.image-gallery {
  display: grid;
  grid-template-columns: 1fr;
  gap: 1rem;
  margin-top: 2rem;

  @media (min-width: 768px) {
    grid-template-columns: repeat(2, 1fr);
    gap: 1.5rem;
  }
}

.gallery-item {
  img {
    width: 100%;
    height: auto;
    border-radius: 4px;
  }
}
</style>
